### ISSUE TITLE
Design Docs Review

### ISSUE THREAD

**Issue by jliversi** [Alaizard/Couch9#1]
Hey Jason, nice work on your docs so far. Here are my notes:

**MVP LIST**

Spots 
- [ ] I'd recommend focusing entirely on the renting side of couchsurfing and simply seeding some users with whom users can stay
- [ ] Therefore, this MVP should change primarily to a show page 

Bookings
- [ ] Once again, I'd focus only on the renting side of the site, and so I wouldn't worry about receiving and accepting booking requests
- [ ] Users should be able to see their upcoming bookings on their dashboard

Spot Search
- [ ] Couchsurfing doesn't seem to have the ability to search by available dates, so search should really just include searching by location.
- [ ] This MVP should include the index page for users.

Reviews
- [ ] I'd recommend slightly modifying the functionality of real couchsurfing and allow people to review right after _making_ a booking. This way, people testing your site don't have to wait a day to come back and see that functionality.

**SCHEMA** 

- [ ] You'll likely need a locations table as both users and spots belong_to locations
- [ ] You'll need a photos table. You should make this a polymorphic association as both users and locations have photos

Users
- [ ] Users need first and last names, and locations. As for locations, I recommend a location_id (see note above) 
- [ ] Users also need age, gender, and a few other columns to represent all of the info that shows on a users show page.

Spots
- [ ] This table needs A LOT more columns. Take a look at a particular "home" on couchsurfing and consider all the columns you'll need to represent that data. Ex. max_num_guests, has_pets, wheelchair_accessible
- [ ] Spots will also need a location_id

Bookings 
- [ ] Need a start_date _and_ end_date

**SAMPLE STATE** 

- [ ] Add all of the relevant information after editting your schema from the notes above.
- [ ] Spots should include an array of associated foreign_keys (ex. booking_ids)
- [ ] "Sort by" doesn't need to be in your state, this can be handled locally by the index component

**BACKEND ROUTES**

- [ ] You don't need a route for reviews as this information should just come up with the relevant users info.
- [ ] For bookings, you only need a post and delete (and potentially a patch? can you edit bookings on couchsurfing?) The rest of the info can come up with the current user when you first fetch them.

**FRONTEND ROUTES** 

- [ ] Here you have routes for events, discussions, friends, travelers_looking, but these aren't part of any other design doc. I think these would all make great bonuses, but you should flesh out the rest of your design docs with details about these.
- [ ] Flesh out your components with relevant subcomponents. Ex. Profile needs a SpotShow component and a ReviewsIndex component (which has a ReviewsIndexItem component). Spend time navigating around on couchsurfing and really try to be as detailed and specific as possible. This will be your roadmap when building out your frontend.

**Comment by Alaizard** [comment]
fixed
